services:
  - type: web
    name: agriguid-backend
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/agriguid-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        value: jdbc:mysql://yamabiko.proxy.rlwy.net:57756/railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ajPBwwlRAvvZHIlJopeVNfMWlmyQmjdy
      - key: CORS_ALLOWED_ORIGINS
        sync: false
